import Head from "next/head";
import { useSelector } from "react-redux";
import Main from "./Main";

// import assets
import styles from "@/assets/css/main.module.css";

export default function Home() {
  const pagePath = useSelector((state) => state.page.path);

  return (
    <>
      <Head>
        <title>
          {pagePath === ""
            ? "Spacecraft"
            : pagePath === "start"
            ? "Loading..."
            : pagePath === "alert"
            ? "Station Status"
            : pagePath === "buyspace"
            ? "Buy Station"
            : pagePath === "buyspacecraft"
            ? "Buy Spacecraft"
            : pagePath === "miningcore"
            ? "Mining Core"
            : pagePath === "databasepage"
            ? "Database"
            : pagePath === "rankingpage"
            ? "Leaderboard"
            : pagePath === "manualpage"
            ? "Manual"
            : pagePath === "managementpage"
            ? "Ships"
            : pagePath === "claimpage"
            ? "Rewards"
            : pagePath === "startbattle"
            ? "BattleShip"
            : "Spacecraft"}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.homeSection}>
        <Main />
      </div>
    </>
  );
}
